version: 2
updates:
  # Enable version updates for Python
  - package-ecosystem: "pip"
    # Look for requirements.txt in the root directory
    directory: "/"
    # Check for updates once a month (reduced frequency)
    schedule:
      interval: "monthly"
    # Disable version updates during active development
    open-pull-requests-limit: 0
    # Group all updates together
    groups:
      dependencies:
        patterns:
          - "*"
    # Limit the number of open pull requests for pip dependencies
    open-pull-requests-limit: 10
    # Add reviewers
    reviewers:
      - "project-maintainer"
    # Add labels
    labels:
      - "dependencies"
      - "security"
    # Set custom commit message
    commit-message:
      prefix: "pip"
      include: "scope"
    # Ignore certain dependencies
    ignore:
      # Ignore updates to cryptography packages unless required for security
      - dependency-name: "cryptography"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-name: "pycryptodome"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    # Disable version updates during active development
    open-pull-requests-limit: 0
    labels:
      - "ci-cd"
      - "dependencies"
