# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 14
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
  - enhancement
  - bug
  - documentation
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs within
  14 days. Thank you for your contributions.
# Comment to post when closing a stale issue
closeComment: >
  This issue has been closed due to inactivity. If you feel this issue
  should be reopened, please create a new issue and reference this one.
# Limit the number of actions per hour
limitPerRun: 30
# Only label issues (not PRs)
only: issues
