name: Security Scan

on:
  workflow_dispatch:  # Only run manually
  # Removed automatic triggers during development

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run Bandit security scan
      run: |
        bandit -r . -x ./venv,./tests -f json -o bandit-results.json || true
        
    - name: Check dependencies for vulnerabilities
      run: |
        safety check -r requirements.txt || true
        
    - name: Upload security scan results
      uses: actions/upload-artifact@v3
      with:
        name: security-scan-results
        path: bandit-results.json
